#!/usr/bin/env bash

# go through all dicom folders. use first dcm to extract
#   id, series_number, ndcm, protocol_name, time, age, sex
# looksl ike
#   110308160921 001 3 circle_localizer 16:15:06.187000 044Y F
#
# will be used by `01_bids` to extract and name nifti files

cd $(dirname $0)
for d in ../raw/*/*; do
  A=($(find $d -type f,l -iname '*dcm' ));
  echo $(basename $(dirname $d)) $(basename $d) ${#A[@]} $(dicom_hinfo -no_name -tag 0018,1030 -tag 0008,0033 -tag 0010,1010 -tag 0010,0040 ${A[0]}|
        perl -slane '$F[1]=~s/(\d{2})(\d{2})([0-9.]+)/\1:\2:\3/; print "@F"');
done | tee txt/times_mr.txt
